# Generated by Django 5.2.7 on 2025-10-18 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('phone_number', models.TextField()),
                ('address', models.TextField()),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('system_creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_update_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (5, 'Deleted')], default=1)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (5, 'Deleted')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image_url', models.TextField(blank=True, null=True)),
                ('system_creation_time', models.DateTimeField(auto_now_add=True)),
                ('system_update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='TableTestingEnumData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(2, 'Inactive'), (1, 'Active'), (5, 'Deleted')], default=1)),
            ],
            options={
                'db_table': 'tablefortest',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_body', models.TextField(blank=True, null=True)),
                ('has_media', models.BooleanField(default=False)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('system_creation_time', models.DateTimeField(auto_now_add=True)),
                ('system_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active'), ('5', 'Deleted')], default='1', max_length=1)),
                ('employees', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='TeamBoardApp.employees')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='TeamBoardApp.project')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (5, 'Deleted')], default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('system_creation_time', models.DateTimeField(auto_now_add=True)),
                ('system_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('employees', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='TeamBoardApp.employees')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='TeamBoardApp.project')),
            ],
            options={
                'db_table': 'project_memberships',
            },
        ),
    ]
