# Generated by Django 5.2.7 on 2025-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employees_test',
            },
        ),
    ]
