# Generated by Django 5.2.7 on 2025-10-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='system_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='system_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='system_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
