# Generated by Django 5.2.7 on 2025-10-13 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBoardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('phone_number', models.TextField()),
                ('address', models.TextField()),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('system_creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('system_update_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active'), ('5', 'Deleted')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
