# Generated by Django 5.2.7 on 2025-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBoardApp', '0002_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(),
        ),
    ]
