# Generated by Django 5.2.7 on 2025-10-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamBoardApp', '0003_alter_employees_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeesTest',
        ),
    ]
